# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 10000

# Change the default prompt format
format = """\
[╭╴](white)$env_var \
$all[╰─](white)$character"""

# Change the default prompt characters
[character]
success_symbol = '[󰜃 ](bright-cyan)'
error_symbol = '[](red)'

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bright-cyan)'
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "white"
style_root = "white"
format = " [$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "@[$hostname](bold yellow) "
disabled = false

[directory]
truncation_length = 0
home_symbol = "󰋞 ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "via [$symbol$branch]($style) "
#truncation_length = 1
#truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "󱧕 "
modified = " "
staged = '[++\($count\)](green)'
renamed = "󰑕 "
deleted = " "

[python]
symbol= ' '
